### ISSUE TITLE
Move `--env=browser` over to `xo` config, or inline env comment

### ISSUE THREAD

**Issue by wooorm** [TimoVerkroost/minor-real-time-web#2]
Currently, editor integrations (like linter-xo, in Atom) don’t pick up on your env setting.
Move it to your [xo config](https://github.com/sindresorhus/xo#envs), or add an [inline comment](http://eslint.org/docs/user-guide/configuring#specifying-environments).

**Comment by TimoVerkroost** [comment]
Thx  for the tip:
fixed it in the repo: https://github.com/TimoVerkroost/minor-real-time-web-api
