### ISSUE TITLE
Inconsistent quote use

### ISSUE THREAD

**Issue by wooorm** [TimoVerkroost/minor-real-time-web#6]
[`views/layout.hbs`](https://github.com/TimoVerkroost/minor-real-time-web/blob/cbac98abf9f6218b26c64f8d86058469f55f021e/views/layout.hbs)

```html
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='/stylesheets/main.min.css' />
```

**Comment by TimoVerkroost** [comment]
Trying to use dubble quotes in HTML files and single quotes in JavaScript.
In this new repo: https://github.com/TimoVerkroost/minor-real-time-web-api

**Comment by wooorm** [comment]
:+1:
