### ISSUE TITLE
More scalable audio-notifications

### ISSUE THREAD

**Issue by wooorm** [TimoVerkroost/minor-real-time-web#7]
There’s a huge if-elseif-else block in [public/javascripts/main.js#L50](https://github.com/TimoVerkroost/minor-real-time-web/blob/cbac98abf9f6218b26c64f8d86058469f55f021e/public/javascripts/main.js#L50). Something like this makes it easier to scale to more easter-eggs:

```js
var sounds = {
  chanel: 'murloc',
  timo: 'goatScream'
}

var sound = sounds[name.toLowerCase()];

if (sound) {
  audioNotification = new Audio('../sounds/' + sound + '.mp3');
  audioNotification.play();
}
```

**Comment by TimoVerkroost** [comment]
You're right, I got it. Much better and better readable.
