### ISSUE TITLE
Too much nesting

### ISSUE THREAD

**Issue by wooorm** [TimoVerkroost/minor-real-time-web#8]
Instead of [wrapping everything in an if-statement](https://github.com/TimoVerkroost/minor-real-time-web/blob/cbac98abf9f6218b26c64f8d86058469f55f021e/public/javascripts/main.js#L4), invert that to keep nesting at a minimum.

As a simplified example:

```js
// Previously
if (foo) {
  // everything here is indented.
}

// Proposed
if (foo) {
  return
}
// everything here is NOT indented.
```

**Comment by TimoVerkroost** [comment]
Thx for the tip, try to use it in the future.
